#spring:
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: dbusername
#    password: dbpassword
#    schema:
#      - order-schema.sql
#      - ingredient-schema.sql
#      - taco-schema.sql
#      - user-schema.sql
#    data:
#      - ingredients.sql

#spring:
#  datasource:
#    jndi-name: java:/comp/env/jdbc/tacoCloudDS

#server:
#  port: 8443
#  ssl:
#    key-store: file:///path/to/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

taco:
  orders:
    page-size: 20